-- Drops para seguridad (en orden de dependencias)

DROP TABLE IF EXISTS CARRITO_DETALLE;
DROP TABLE IF EXISTS CARRITO;
DROP TABLE IF EXISTS P_ELIMINADOS;
DROP TABLE IF EXISTS M_ELIMINADOS;
DROP TABLE IF EXISTS CAT_ELIMINADOS;
DROP TABLE IF EXISTS DETALLE_FACTURA;
DROP TABLE IF EXISTS FACTURA;
DROP TABLE IF EXISTS PRODUCTO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS MARC_CATEG;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS RANGO;

-- Creacion de tablas

CREATE TABLE IF NOT EXISTS MARCA (
    idMarca VARCHAR(10) PRIMARY KEY,
    nombMarca VARCHAR(25) NOT NULL
);


CREATE TABLE IF NOT EXISTS CATEGORIA (
    idCategoria VARCHAR(10) PRIMARY KEY,
    nombCategoria VARCHAR(25) NOT NULL,
    imagen VARCHAR(255) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS MARC_CATEG(
    idMarcCat INT AUTO_INCREMENT,
    idMarca VARCHAR(10),
    idCategoria VARCHAR(10),
    PRIMARY KEY (idMarcCat),
    FOREIGN KEY (idMarca) REFERENCES MARCA(idMarca),
    FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria),
    UNIQUE KEY unique_marca_categoria (idMarca, idCategoria)
);

CREATE TABLE IF NOT EXISTS RANGO (
    idRango TINYINT PRIMARY KEY,
    nombRango VARCHAR(25) NOT NULL,
    CONSTRAINT idRango_CHK CHECK (idRango IN (0, 1))
);

CREATE TABLE IF NOT EXISTS USUARIO(
    idUsuario VARCHAR(20) PRIMARY KEY,
    nombUsuario VARCHAR(50) NOT NULL,
    passUsuario VARCHAR(50) UNIQUE NOT NULL,
    emailUsuario VARCHAR(50) NOT NULL,
    idRango TINYINT NOT NULL DEFAULT 0,
    FOREIGN KEY (idRango) REFERENCES RANGO(idRango)
);


CREATE TABLE IF NOT EXISTS PRODUCTO (
    idProducto VARCHAR(30) PRIMARY KEY,
    nombProducto VARCHAR(25) NOT NULL,
    modelo VARCHAR(25) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    imagen VARCHAR(255) DEFAULT NULL,
    idMarca VARCHAR(10) NOT NULL,
    idCategoria VARCHAR(10) NOT NULL,
    FOREIGN KEY (idMarca) REFERENCES MARCA(idMarca),
    FOREIGN KEY (idCategoria) REFERENCES CATEGORIA(idCategoria)
);

CREATE TABLE IF NOT EXISTS FACTURA (
    idFactura VARCHAR(30) PRIMARY KEY,
    fecha DATE NOT NULL,
    hora TIME NOT NULL,
    idUsuario VARCHAR(20) NOT NULL,
    FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario)

);

CREATE TABLE IF NOT EXISTS DETALLE_FACTURA (
    idDetalleFactura VARCHAR(50) PRIMARY KEY,
    idFactura VARCHAR(30) NOT NULL,
    idProducto VARCHAR(30) NOT NULL,
    cantidad INT NOT NULL,
    precioTotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (idFactura) REFERENCES FACTURA(idFactura),
    FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto)
);

CREATE TABLE IF NOT EXISTS CARRITO(
    idCarrito VARCHAR(30) PRIMARY KEY,
    idUsuario VARCHAR(20) NOT NULL,
    FOREIGN KEY (idUsuario) REFERENCES USUARIO(idUsuario)
);

CREATE TABLE IF NOT EXISTS CARRITO_DETALLE(
    idCarritoDetalle VARCHAR(50) PRIMARY KEY,
    idCarrito VARCHAR(30) NOT NULL,
    idProducto VARCHAR(30) NOT NULL,
    cantidad INT NOT NULL,
    precioTotal DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (idCarrito) REFERENCES CARRITO(idCarrito),
    FOREIGN KEY (idProducto) REFERENCES PRODUCTO(idProducto)
);


CREATE TABLE IF NOT EXISTS P_ELIMINADOS (
    idElimProduc VARCHAR(50) PRIMARY KEY,
    idProducto VARCHAR(30) UNIQUE NOT NULL,
    nombProducto VARCHAR(25) NOT NULL,
    modelo VARCHAR(25) NOT NULL,
    precio DECIMAL(10,2) NOT NULL,
    stock INT NOT NULL,
    imagen VARCHAR(255) DEFAULT NULL,
    idMarca VARCHAR(10) NOT NULL,
    idCategoria VARCHAR(10) NOT NULL,
    fechaEliminacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS M_ELIMINADOS (
    idElimMarca VARCHAR(20) PRIMARY KEY,
    idMarca VARCHAR(10) UNIQUE NOT NULL,
    nombMarca VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS CAT_ELIMINADOS (
    idElimCateg VARCHAR(20) PRIMARY KEY,
    idCategoria VARCHAR(10) UNIQUE NOT NULL,
    nombCategoria VARCHAR(25) NOT NULL,
    imagen VARCHAR(255) DEFAULT NULL,
    fechaEliminacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

